# fly.toml app configuration file generated for protocol-kitchen-sink on 2023-10-18T14:50:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "protocol-kitchen-sink"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
